### ISSUE TITLE
Use ComponentDefinition/ModuleDefinition terms in API

### ISSUE THREAD

**Issue by cjmyers** [ICO2S/sbolstack-client-java#4]
When the API is referring to CDs or MDs, it should use the full name rather than Component/Module as these have different meaning in the standard and could lead to confusion.

**Comment by jamesamcl** [comment]
Agreed - this is quite a substantial change because it requires changing the backend as well as the client, and I'll have to do both at the same time, but I'll get onto it this week.

**Comment by cjmyers** [comment]
Done
