### ISSUE TITLE
Ensure compliant sbol

### ISSUE THREAD

**Issue by michael13162** [ICO2S/sbolstack-client-java#7]
A lot of the data has URIs with information on displayId, but the actual displayId field is empty.  Would it be possible to ensure best practices/compliance on the data?

**Comment by jamesamcl** [comment]
I'd rather keep the Stack completely agnostic of the data it stores, but I will fix the iGEM dataset to add display IDs.  Leaving issue open until I do.

**Comment by cjmyers** [comment]
Closing.
